# *************************************************************
# Fach	  BSy
# Autor   M. Thaler
# Stand   11/2014
# Version v.fs20
# *************************************************************

CMP=		gcc
CMPFLAGS=       -Wall
LDFLAGS=
EXENAM1=	ProcA2.e
FNAM1=		ProcA2
LIBNAME=

$(EXENAM1):	$(FNAM1).o
		$(CMP)  $(FNAM1).o $(LIBNAME) $(LDFLAGS) -o $@

.c.o:
		$(CMP) -c $(CMPFLAGS) $<

.cc.o:
		$(CMP) -c $(CMPFLAGS) $<

clean:
		rm -f *.o $(EXENAM1)

all:
		@make clean
		@make


