HTTP/1.1 200 OK Server: nginx/1.19.1 Date: Wed, 14 Oct 2020 08:09:40 GMT Content-Type: application/fhir+json; fhirVersion=3.0; charset=utf-8 Content-Length: 359 Connection: close Last-Modified: Wed, 14 Oct 2020 08:09:40 GMT ETag: W/"399f1de0-8183-418c-bfae-9b9719f7c336" Request-Context: appId=cid-v1:36fd023f-c59d-4b79-903a-69140e19211c Strict-Transport-Security: max-age=15724800; includeSubDomains { "resourceType": "OperationOutcome", "id": "f08a8207-d8f0-41ad-991f-9fde9871dc4f", "meta": { "versionId": "399f1de0-8183-418c-bfae-9b9719f7c336", "lastUpdated": "2020-10-14T08:09:40.172+00:00" }, "issue": [ { "severity": "information", "code": "informational", "diagnostics": "The operation was successful" } ] }