HTTP/1.1 201 Created Server: nginx/1.19.1 Date: Wed, 14 Oct 2020 07:55:27 GMT Content-Type: application/fhir+json; fhirVersion=3.0; charset=utf-8 Content-Length: 538 Connection: close Last-Modified: Wed, 14 Oct 2020 07:55:27 GMT ETag: W/"e40801eb-66c3-4433-8968-e7f2d10e49ad" Location: https://vonk.fire.ly/Patient/b720bbfc-1ad7-4eaa-89cc-60daf261367c/_history/e40801eb-66c3-4433-8968-e7f2d10e49ad Request-Context: appId=cid-v1:36fd023f-c59d-4b79-903a-69140e19211c Strict-Transport-Security: max-age=15724800; includeSubDomains  {  "resourceType": "Patient",  "identifier": [  {  "use": "usual",  "value": "Abc123"  }  ],  "name": [  {  "use": "usual",  "text": "Franz Muster"  }  ],  "gender": "male",  "address": [  {  "use": "home",  "type": "both",  "text": "Leidensweg 10, 9876 Specimendorf"  }  ],  "birthDate": "1967-10-02",  "id": "b720bbfc-1ad7-4eaa-89cc-60daf261367c",  "meta": {  "versionId": "e40801eb-66c3-4433-8968-e7f2d10e49ad",  "lastUpdated": "2020-10-14T07:55:27.052+00:00"  } }