
      <patient classCode="PAT">
                <id assigningAuthorityName="SPID" extension="761337610435209810" root="2.16.756.5.30.1.127.3.10.3"/>
                <id assigningAuthorityName="CHFACILITY" extension="CHFACILITY9810" root="1.3.6.1.4.1.12559.11.25.1.19"/>
    
    
  
  

