#!/bin/bash
# M. Thaler, InIT/ZHAW 11/2014
# Version v.fs20

if test "$1" = ""
then
    cmd="-a"
else
    cmd="-C $1"
fi

forever="1"
while test "$forever" = "1"
do
    clear
    ps $cmd
    sleep 1
done

